name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.0.1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: pyoxidizer
      - name: Build Hydrus
        run: |
          cd $GITHUB_WORKSPACE
          basename $(rustc --print sysroot) | sed -e "s/^stable-//" > triple.txt
          pyoxidizer build --release
          cd build/$(head -n 1 triple.txt)/release/install
          tar -czf hydrus-linux.tgz *
          mv *.tgz $GITHUB_WORKSPACE
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: hydrus-linux-tarball
          path: hydrus-linux.tgz
          if-no-files-found: error
  
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.0.1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: pyoxidizer
      - name: Build Hydrus
        run: |
          cd $GITHUB_WORKSPACE
          basename $(rustc --print sysroot) | sed -e "s/^stable-//" > triple.txt
          pyoxidizer build --release
          cd build/$(head -n 1 triple.txt)/release/install
          tar -czf hydrus-macos.tgz *
          mv *.tgz $GITHUB_WORKSPACE
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.1
        with:
          name: hydrus-linux-tarball
          path: hydrus-macos.tgz
          if-no-files-found: error

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.0.1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: rust-cargo
        uses: actions-rs/cargo@v1.0.1
        with:
          command: install
          args: pyoxidizer
      - name: Build Hydrus
        run: |
          cd $GITHUB_WORKSPACE
          pyoxidizer build --release
